// Package product provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package product

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Product defines model for Product.
type Product struct {
	// CreateOn The date that the product was created.
	CreateOn *openapi_types.Date `json:"createOn,omitempty"`

	// DeletedOn The date that the product was deleted.
	DeletedOn   *openapi_types.Date `json:"deletedOn,omitempty"`
	Description string              `json:"description"`

	// Id Unique identifier for the given product.
	Id    int     `json:"id"`
	Name  string  `json:"name"`
	Price float32 `json:"price"`
	Sku   string  `json:"sku"`

	// UpdatedOn The date that the product was updated.
	UpdatedOn *openapi_types.Date `json:"updatedOn,omitempty"`
}

// PostProductJSONBody defines parameters for PostProduct.
type PostProductJSONBody struct {
	CreatedOn   *openapi_types.Date `json:"createdOn,omitempty"`
	DeletedOn   *openapi_types.Date `json:"deletedOn,omitempty"`
	Description *string             `json:"description,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Price       *int                `json:"price,omitempty"`
	Sku         *string             `json:"sku,omitempty"`
	UpdatedOn   *openapi_types.Date `json:"updatedOn,omitempty"`
}

// PatchProductsProductIdJSONBody defines parameters for PatchProductsProductId.
type PatchProductsProductIdJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`

	// Price Without tax
	Price *int32  `json:"price,omitempty"`
	Sku   *string `json:"sku,omitempty"`
}

// GetProductsJSONBody defines parameters for GetProducts.
type GetProductsJSONBody = map[string]interface{}

// PostProductJSONRequestBody defines body for PostProduct for application/json ContentType.
type PostProductJSONRequestBody PostProductJSONBody

// PatchProductsProductIdJSONRequestBody defines body for PatchProductsProductId for application/json ContentType.
type PatchProductsProductIdJSONRequestBody PatchProductsProductIdJSONBody

// GetProductsJSONRequestBody defines body for GetProducts for application/json ContentType.
type GetProductsJSONRequestBody = GetProductsJSONBody
